//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECOCSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPL
    {
        public int CTPLID { get; set; }
        public int CTPLTermID { get; set; }
        public int VehicleClassificationID { get; set; }
        public decimal BasicPremium { get; set; }
        public decimal VAT { get; set; }
        public decimal DST { get; set; }
        public decimal LGT { get; set; }
        public decimal Taxes { get; set; }
        public decimal AuthenticationFee { get; set; }
        public decimal GrossPremium { get; set; }
        public bool Active { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
