//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECOCSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPLApplication
    {
        public int ID { get; set; }
        public string COC { get; set; }
        public Nullable<System.DateTime> COCInceptionDate { get; set; }
        public Nullable<System.DateTime> COCExpirationDate { get; set; }
        public Nullable<decimal> COCBasicPremium { get; set; }
        public Nullable<decimal> COCVAT { get; set; }
        public Nullable<decimal> COCDST { get; set; }
        public Nullable<decimal> COCLGT { get; set; }
        public Nullable<decimal> COCTaxes { get; set; }
        public Nullable<decimal> COCAuthenticationFee { get; set; }
        public Nullable<decimal> COCPremium { get; set; }
        public string COCPolicyNumber { get; set; }
        public string COCContentType { get; set; }
        public byte[] COCByte { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public Nullable<int> VehicleClassificationID { get; set; }
        public Nullable<int> TaxTypeID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ClientAddressID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CompanyBranchID { get; set; }
        public Nullable<int> RegistrationTypeID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
