//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECOCSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCOCSeries
    {
        public int InsuranceCOCSeriesID { get; set; }
        public int InsuranceID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public int SeriesFrom { get; set; }
        public int SeriesTo { get; set; }
        public int CurrentSeries { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string MasterPolicy { get; set; }
        public string COCPrefix { get; set; }
    }
}
