//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECOCSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleInfo
    {
        public int VehicleID { get; set; }
        public string EngineNumber { get; set; }
        public string ChassisNumber { get; set; }
        public string PlateNumber { get; set; }
        public string Year { get; set; }
        public string Color { get; set; }
        public string MVFileNumber { get; set; }
        public Nullable<int> MVTypeID { get; set; }
        public Nullable<int> MakeID { get; set; }
        public Nullable<int> VariantID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> VehicleColorID { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public Nullable<int> ClassificationID { get; set; }
    }
}
